[package]
name = "lsr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = "4.5"
tabular = "0.2"
users = "0.11"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
pretty_assertions = "1.4"
rand = "0.9"
