[package]
name = "commr"
version = "0.1.0"
edition = "2024"
authors = ["TestAquatic"]
description = "`comm`의 간단한 러스트 버전"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
pretty_assertions = "1.4"
rand = "0.9"
