[package]
name = "tailr"
version = "0.1.0"
edition = "2024"
authors = ["TestAquatic"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
num = "0.4"
regex = "1.11"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
pretty_assertions = "1.4"
rand = "0.9"
